Test that the 'bosh' CLI is properly added to the image

diff --git a/ci/settings.yml b/ci/settings.yml
--- a/ci/settings.yml
+++ b/ci/settings.yml
@@ -114,6 +114,12 @@ jobs:
 
                 failure="false"
 
+                if [[ $(bosh --version) != "version "* ]]; then
+                    >&2 echo "FAIL: expected 'bosh --version' to work, but got:"
+                    (bosh --version | cat) || true
+                    failure="true"
+                fi
+
                 out_dir=/tmp/mocked-bosh-cli
 
                 mv /usr/bin/bosh /usr/bin/bosh.bak
